### ISSUE TITLE
sounddevice.PortAudioError: Error opening Stream: Device unavailable [PaErrorCode -9985]

### ISSUE THREAD

**Issue by CH-Wong** [spmvg/backlooper_backend#1]
SYSTEM INFO
OS: Windows 11
Python Version: 3.11.8
Backlooper version: 0.0.1
DAW:  Ableton 11.3.22
Audio Interface: N/A
MIDI Controller: AKAI LPK-25
Audio Drivers: ASIO4ALL 2.15
Earphones: DT 770 PRO (80Ohm) mini-jack plug

HOW TO RECREATE BUG:
1. Start new python environment `python -m venv venv`
2. Activate virtual environment
3. Install back-end package `python -m pip install backlooper`
4. Plug-in headphones mini-jack
5. Start Ableton
6. Start back-end package `python -m backlooper`
7. Get error

BUG DESCRIPTION
Back-end program immediately errors out 
```
(venv) PS C:\Users\wchun\Desktop> python -m backlooper
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\wchun\Desktop\venv\Lib\site-packages\backlooper\audio.py", line 177, in run
    with Stream(
         ^^^^^^^
  File "C:\Users\wchun\Desktop\venv\Lib\site-packages\sounddevice.py", line 1800, in __init__
    _StreamBase.__init__(self, kind='duplex', wrap_callback='array',
  File "C:\Users\wchun\Desktop\venv\Lib\site-packages\sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "C:\Users\wchun\Desktop\venv\Lib\site-packages\sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening Stream: Device unavailable [PaErrorCode -9985]
```

Without plugging in headphones, there is no problem. 

```
(venv) PS C:\Users\wchun\Desktop> python -m backlooper
1714405858.0410175 - INFO - backlooper.audio - Using input device: Microphone Array (Intel® Smart 
1714405858.0410175 - INFO - backlooper.audio - Using output device: Speakers (Realtek(R) Audio)
1714405858.042018 - INFO - backlooper.audio - If an input or output device should be changed, please adjust the current settings of the OS and restart this application. The default input and output device will be taken.   
```

**Comment by spmvg** [comment]
Hi @CH-Wong,

Thanks for reporting an issue! The "Device unavailable" could be caused by another application (Ableton?) claiming the audio device. I've been able to run the backend successfully on my laptop both with built-in speakers and audio jack headphones (although it works best with an audio interface). This raises some follow up questions from my side:

* Does the error happen if you don't run Ableton at the same time?
* What is the default audio device (on Windows that is Settings -> System -> Sound) in both cases? Backlooper will take the audio device configured in the OS.

If any of these resolve the issue, I'll add some more background about the audio device behaviour in the frontend.

**Comment by CH-Wong** [comment]
Testing without Ableton on seems to fix the problem, I can now hear the click-track on the headphones. Am I supposed to use this package without an external DAW?

**Comment by spmvg** [comment]
Interesting, so then indeed it looks like another application was hogging the audio device. I've been trying to reproduce what you describe and I haven't been able to. I've tried running backlooper side by side with Ableton or Audacity on the same audio device, and didn't get errors. So it looks like Ableton for some reason is hogging the audio device on your setup.

> Am I supposed to use this package without an external DAW?

I am not sure why you would want to use Ableton side by side on the same audio device? Can you elaborate (maybe draw the setup)? It sounds to me like driving two cars at the same time: either use Ableton, or use backlooper to make some quick-and-dirty loops.

**Comment by spmvg** [comment]
Closing due to lack of activity. Please recreate if needed.
